In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [2]:
!nvidia-smi

Fri Feb 28 06:20:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [16]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# **Random tensors**

Why random tensors?

 Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

 Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [4]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5476, 0.0661, 0.6315, 0.4521],
        [0.9784, 0.5854, 0.2775, 0.6958],
        [0.9742, 0.1429, 0.5103, 0.7453]])

In [5]:
random_tensor.ndim

2

**Note** - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [7]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# **Zeros and Ones**

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
ex = zeros * random_tensor
ex

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
ex1 = ones * random_tensor
ex1

tensor([[0.5476, 0.0661, 0.6315, 0.4521],
        [0.9784, 0.5854, 0.2775, 0.6958],
        [0.9742, 0.1429, 0.5103, 0.7453]])

In [10]:
ones.dtype

torch.float32

In [14]:
random_tensor.dtype

torch.float32

## **Creating a range of tensors and tensors-like**





In [15]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-15-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
# Use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Note:** https://pytorch.org/docs/stable/generated/torch.arange.html

In [6]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=100, step=6)
one_to_ten

tensor([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [7]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# **Tensor datatypes**
 **Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [8]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

**Note:** https://pytorch.org/docs/stable/tensors.html

In [9]:
float_32_tensor.dtype

torch.float32

In [10]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [11]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [12]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [13]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# **Getting information from tensors (tensor attributes)**
1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [15]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3515, 0.7090, 0.4206, 0.3182],
        [0.5496, 0.2752, 0.3477, 0.1728],
        [0.3978, 0.2422, 0.4961, 0.3860]])

In [16]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3515, 0.7090, 0.4206, 0.3182],
        [0.5496, 0.2752, 0.3477, 0.1728],
        [0.3978, 0.2422, 0.4961, 0.3860]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
